test3/person/urls.py
from django.urls import path, include
from django.conf.urls import url
from person import views

app_name = 'person'

urlpatterns = [
    path('', views.DisplayOrder, name='order_sale'),
    path('logout/', views.user_logout, name='logout'),
    path('user_login/', views.user_login, name='user_login'),
    path('register/', views.register, name='register'),
    # url(r'^notifications/', include('notify.urls', 'notifications')),
]

test3/test3/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from person import views


urlpatterns = [
    
    path('admin/', admin.site.urls),
    url(r'^notifications/', include('notify.urls', 'notifications')),
    path('', include('person.urls',namespace='person')),
]

test3/person/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from datetime import *
from django.contrib.auth.models import User


class User(models.Model):
    
    user = models.OneToOneField(User,on_delete=models.CASCADE,)
    
    def __str__(self):
        return self.user.username


class OrderSale(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)
    invoiceNumber = models.CharField(max_length=50,unique=True)
    invoiceDate = models.DateTimeField(default=datetime.now())
    shipmentDate = models.DateField(blank=True, null=True)
    dueDate = models.DateField(blank=True, null=True)
    shippingAddress=models.TextField(blank=True, null=True)
    billingAddress=models.TextField(blank=True, null=True) 
    otherDetails = JSONField(blank=True, null=True) 


    def __str__(self):
        return self.invoiceNumber

test3/person/forms.py
from django import forms
from person.models  import User
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):

    password = forms.CharField(widget= forms.PasswordInput())
    
    class Meta():
        model = User
        fields = ('username','email','password')

        widgets = {

        }

test3/person/views.py
from django.shortcuts import render
from person.models import OrderSale, User 
from django.db import models
from django_tables2 import RequestConfig
from .tables import OrderTable
from .filters import SaleFilter
from django.db.models.functions import Extract, Substr, Cast
from django.contrib.postgres.fields.jsonb import KeyTextTransform
from django.contrib.auth import login, authenticate, logout
from person.forms import UserForm
from django.contrib.auth.decorators import login_required
from notify.signals import notify


def DisplayOrder(request):

    user = User.objects.get(id=1)
    # user = list(User.objects.all())
    print(user)

    if request.GET.get('notify'):
        print('notify clicked')
        print(request.user)
        notify.send(request.user, recipient=request.user, actor=request.user,
                verb='notified')#, nf_type='followed_by_one_user')

    queryset = OrderSale.objects.annotate(Extra= Substr('name',1,6),val=KeyTextTransform('order_name','otherDetails'),order_name=Cast('otherDetails', models.TextField()),)
    f = SaleFilter(request.GET, queryset=queryset)
    table = OrderTable(f.qs)
    RequestConfig(request, paginate={"per_page": 100, "page": 1}).configure(table)
    return render(request, 'order_sale.html', {'table': table, 'filter': f})




def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                queryset = OrderSale.objects.annotate(Extra= Substr('name',1,6),val=KeyTextTransform('order_name','otherDetails'),order_name=Cast('otherDetails', models.TextField()),)
                f = SaleFilter(request.GET, queryset=queryset)
                table = OrderTable(f.qs)
                RequestConfig(request, paginate={"per_page": 100, "page": 1}).configure(table)
                return render(request, 'order_sale.html', {'table': table, 'filter': f})
                # return render(request,'order_sale.html')

            else:
                return HttpResponse('Account not active')
        else:
            print('Someone tried to login and failed!')
            print('username: {} and password: {}'.format(username,password))
            queryset = OrderSale.objects.annotate(Extra= Substr('name',1,6),val=KeyTextTransform('order_name','otherDetails'),order_name=Cast('otherDetails', models.TextField()),)
            f = SaleFilter(request.GET, queryset=queryset)
            table = OrderTable(f.qs)
            RequestConfig(request, paginate={"per_page": 100, "page": 1}).configure(table)
            return render(request, 'order_sale.html', {'table': table, 'filter': f})
            # return render(request,'order_sale.html')

    else:
        return render(request,'login.html',{})

@login_required
def user_logout(request):
    logout(request)
    queryset = OrderSale.objects.annotate(Extra= Substr('name',1,6),val=KeyTextTransform('order_name','otherDetails'),order_name=Cast('otherDetails', models.TextField()),)
    f = SaleFilter(request.GET, queryset=queryset)
    table = OrderTable(f.qs)
    RequestConfig(request, paginate={"per_page": 100, "page": 1}).configure(table)
    return render(request, 'order_sale.html', {'table': table, 'filter': f})
    # return render(request,'order_sale.html')

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            registered = True
        else:
            print(user_form.errors)

    else:
        user_form = UserForm()

    return render(request,'register.html',
                            {'user_form':user_form,
                              'registered':registered})

test3/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>
        <!-- {% load notification_tags %}
        {% user_notifications %}
        {% user_notifications for box %} -->
    <h1>Please Login</h1>
    <br>
    <form action="{% url 'person:user_login' %}" method="post">
        {% csrf_token %}

        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">
    </form>
    <a href="{% url 'person:order_sale' %}">Back</a>
</body>
</html>

test3/templates/notifications/all.html
{% extends "notifications/base.html" %}
{% load i18n %}
{% load notification_tags %}
{% block title %}{% trans "Notifications" %}{% endblock %}
{% block content %}
    <hr>
    <button class="mark-all-notifications" data-mark-action="read">{% trans "Mark all as read" %}</button>
    <button class="mark-all-notifications" data-mark-action="unread">{% trans "Mark all as unread" %}</button>
    <ul class="notifications list-group">
    {% if notifications %}
    {% render_notifications using notifications %}
    {% endif %}
    </ul>
{% endblock %}

test3/templates/notifications/base.html
{% load staticfiles %}
{% load notification_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.5/yeti/bootstrap.min.css" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
      <!-- HTML5 shim and Respond.js for IE8 support of HTML5
         elements and media queries -->
      <!-- WARNING: Respond.js doesn't work if you view the
         page via file:// -->

      <!--[if lt IE 9]>
      <script src = "//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src = "//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->

    <!-- inclusion of extra head tags. -->
    {% block extrahead %}
        {% include_notify_js_variables %}
    {% endblock %}
    <!-- end -->
</head>
<body>

<!-- navbar -->
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'person:order_sale' %}">MYSite</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">

                <li><a href="#">menu</a></li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>

            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false"><i class="glyphicon glyphicon-globe"></i></a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="notificationPanel"
                                 style="position:relative; width: 100%; overflow: hidden;  min-width: 300px;">
                                <div class="notificationContent" style="overflow-y: scroll; height: 100%;">
                                    <ul class="notification-box-list" style="margin:0; padding:0;list-style-type: none;">
                                        {% render_notifications using user.notifications.active.prefetch for box %}
                                        <li style="background-color: #ddd; padding: 5px; text-align: center;">
                                            <a href="#" style="color: black;">All Notifications</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- end navbar -->

<!-- alerts -->
<div id="messages">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                <a class="close" data-dismiss="alert">x</a>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
</div>
<!-- end alerts -->

<!-- body container -->
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<!-- end body container -->

<!-- footer -->
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <p>Page © - 2015 <strong>MySite</strong></p>
            </div>
        </div>
    </div>
</footer>
<!-- end footer -->

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src ="{% static 'notify/notifyX.js' %}"></script>

<!-- script inclusions -->
{% block extrascripts %}
{% endblock %}
<!-- end script inclusions -->
</body>
</html>

test3/templates/notifications/includes/default.html
{% load i18n %}
<li data-nf-id="{{ notification.id }}" id="nf-{{ notification.id }}" class="notification list-group-item {{ notification.read|yesno:'read,unread' }}">
{% block notification %}
    {% if notification.target %}
        {% blocktrans with actor_url=notification.actor_url actor=notification.actor verb=notification.verb target=notification.target target_url=notification.target_url%}
            <a href="{{ actor_url }}">{{ actor }}</a> {{ verb }} on <a href="{{ target_url }}">{{ target }}</a>
        {% endblocktrans %}
    {% else %}
        {% blocktrans with actor_url=notification.actor_url actor=notification.actor verb=notification.verb%}
            <a href="{{ actor_url }}">{{ actor }}</a> {{ verb }}
        {% endblocktrans %}
    {% endif %}
    <span class="timesince">{% blocktrans with created=notification.created|timesince %}{{created}} ago{% endblocktrans %}</span>
{% endblock notification %}
    <button data-id="{{ notification.id }}" class="mark-notification"
            data-mark-action="{{ notification.read|yesno:'unread,read' }}"
            data-toggle-text="{% blocktrans with read=notification.read|yesno:_('read,unread') %}Mark as {{ read }}{% endblocktrans %}">
        {% blocktrans with read=notification.read|yesno:_('unread,read') %}Mark as {{ read }}{% endblocktrans %}
    </button>

    <button class="delete-notification" data-id="{{ notification.id }}">
        X
    </button>
</li>

test3/templates/notifications/includes/default_box.html
{% include "notifications/includes/default.html" %}
<!-- n-rTt-bx -->

test3/templates/notifications/includes/js_variables.html
{% if user.is_authenticated %}
    <script type="text/javascript">
        // Ajax-Notification related callback urls.
        var updateNotificationUrl = "{{ update_notification }}";
        var markNotificationUrl = "{{ mark_notification }}";
        var markAllNotificationUrl = "{{ mark_all_notification }}";
        var deleteNotificationUrl = "{{ delete_notification }}";

        // Jquery class selectors.
        var nfListClassSelector = "{{ nf_list_class_selector }}";
        var nfClassSelector = "{{ nf_class_selector }}";
        var nfBoxListClassSelector = "{{ nf_box_list_class_selector }}";
        var nfBoxClassSelector = "{{ nf_box_class_selector }}";

        var markNotificationSelector = "{{ nf_mark_selector }}";
        var markAllNotificationSelector = "{{ nf_mark_all_selector }}";
        var deleteNotificationSelector = "{{ nf_delete_selector }}";

        var readNotificationClass = "{{ nf_read_class }}";
        var unreadNotificationClass = "{{ nf_unread_class }}";

        var notificationUpdateTimeInterval = "{{ nf_update_time_interval }}";

        //functions to handle ajax success.
        {% include "notifications/includes/update_success.js" %}
        {% include "notifications/includes/mark_success.js" %}
        {% include "notifications/includes/mark_all_success.js" %}
        {% include "notifications/includes/delete_success.js" %}
    </script>
{% endif %}

test3/templates/order_sale.html
<!DOCTYPE html>
{% load render_table from django_tables2 %}
{% load static %}
{% load notification_tags %}
{% include_notify_js_variables %}

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Detail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/main.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'notify/notifyX.js' %}"></script>
</head>

<body >
        <div class="navbar-nav container"> 
                <a class="nav-item nav-link" href="{% url 'person:register' %}"><i class="fa fa-fw fa-user"></i> SignUp</a>
                {% if user.is_authenticated %}
                <li><a class="nav-link" href="{% url 'person:logout' %}">Logout</a></li>
                <li><a class="nav-link" href="notifications/all">Notifications</a></li>
                {% else %}
                <li><a class="nav-link" href="{% url 'person:user_login' %}">Login</a></li>
                {% endif %}
              </div>
    <div class="container jumbotron">
            <form action="" method="get">
                    <button value='notify' name="notify">Notify</button>
            </form>
            <ul class="notification-box-list"></ul>
            <!-- {% user_notifications %} -->
            
            <!-- {% user_notifications for box %} -->
    <form class="container" action="" method="get">
            <h2>Order Sale</h2>
        {{ filter.form }}
        <!-- <input type="text" name="search"> -->
        <input type="submit" value="Search"/>
    </form>
    <br>
</div>
    {% render_table table %}
    <!-- {% for i in  filter.qs %}
    {{ i.name }} ,{{ i.Extra }} <br>
    {% endfor %} -->
    <!-- {% if val != 0 %}
    {% render_table filter.qs %}
    {% else %}
    {% render_table table %}
    {% endif %} -->


</body>

</html>

test3/templates/register.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Register</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css">
    <script src="main.js"></script>
</head>
<body>
    
    {% if registered %}
    <h1>Thank you for registering!</h1>
    <a href="{% url 'person:order_sale' %}">Home</a>
    {% else %}
    
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <div class="container">
            {{ user_form.as_p }}
            <p>By creating an account you agree to our <a href="#" >Terms & Privacy</a>.</p>
            <a href="{% url 'person:order_sale' %}" class="button" >Cancel</a>
            <input type="submit" name="" value="Register" >
        </div>
    </form>
    {% endif %}
    <!-- <a href="{% url 'person:order_sale' %}">Back</a> -->
</body>
</html>